const String emailField = 'email'; 
const String nameField = 'name';
const String usernameField = 'username';
const String locationField = 'location';
const String photoUrlField= 'photoUrl';
const String createdAtField = 'createdAt';
const String swapCountField = 'swapCount';
const String totalRatingStarsField = 'totalRatingStars';
const String numberOfRatingsField = 'numberOfRatings';