name: swapparel
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  random_string: ^2.3.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_card_swiper: ^7.0.2
  go_router: ^15.1.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/boy.jpg
   - assets/woman.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700