name: swapparel
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  flutter_card_swiper: ^7.0.2
  go_router: ^15.1.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  timeago: ^3.7.1
  collection: ^1.19.1
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/



flutter_native_splash:
  color: "#F7F8ED"
  
  color_dark: "#1c3d2b" 

  image: assets/splash/logo.png


  
  android_12:
    icon_background_color: "#f7f8ed"
    icon_background_color_dark: "#1c3d2b"

    image: assets/splash/logo.png

  
  web:
    color: "#f7f8ed"
    color_dark: "#1c3d2b"
    image: assets/splash/logo.png
    image_dark: assets/splash/logo_dark.png


flutter_launcher_icons:
  # --- Configuración para Android ---
  android: "launcher_icon" 
  image_path:  "assets/launcher/icon.png" 
  adaptative_icon_foreground: "assets/launcher/icon.png" 
  adaptative_icon_background: "#f7f8ed"
  min_sdk_android: 23 

  # --- Configuración para iOS ---
  ios: true 
  image_path_ios: "assets/launcher/icon.png"
  remove_alpha_ios: true 
 

  web:
    generate: true
    image_path: "assets/launcher/icon.png"
    
  windows:
    generate: true
    image_path: "assets/launcher/icon.png"
  
  macos:
    generate: true
    image_path: "assets/launcher/icon.png"