// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGDbQmAPN98psrosObwbnJg5P2jZu4cQ0',
    appId: '1:1044413000346:web:12ce87f6d2a64b6026cd23',
    messagingSenderId: '1044413000346',
    projectId: 'chatapp-e153d',
    authDomain: 'chatapp-e153d.firebaseapp.com',
    storageBucket: 'chatapp-e153d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Y-d5M-6sIEjkEJ16dilh7Zne4aAJl1A',
    appId: '1:1044413000346:android:0d84df2d1080207d26cd23',
    messagingSenderId: '1044413000346',
    projectId: 'chatapp-e153d',
    storageBucket: 'chatapp-e153d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGDbQmAPN98psrosObwbnJg5P2jZu4cQ0',
    appId: '1:1044413000346:web:1e532a01b2806dd726cd23',
    messagingSenderId: '1044413000346',
    projectId: 'chatapp-e153d',
    authDomain: 'chatapp-e153d.firebaseapp.com',
    storageBucket: 'chatapp-e153d.firebasestorage.app',
  );
}
